apiVersion: v1
kind: Service
metadata:
  name:  {{ include "zwavejs2mqtt.fullname" . }}
  labels:
    {{- include "zwavejs2mqtt.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8091
      targetPort: http
    - name: websocket
      port: 3000
      targetPort: websocket
  selector:
    name:  {{ include "zwavejs2mqtt.fullname" . }}
