apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zwavejs2mqtt.fullname" . }}
  labels:
    {{- include "zwavejs2mqtt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ include "zwavejs2mqtt.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "zwavejs2mqtt.fullname" . }}
    spec:
      containers:
      - name: zwavejs2mqtt
        image: zwavejs/zwave-js-ui:latest
#        livenessProbe:
#          failureThreshold: 10
#          httpGet:
#            httpHeaders:
#            - name: Accept
#              value: text/plain
#            path: /health
#            port: http
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
        ports:
        - containerPort: 8091
          name: http
          protocol: TCP
        - containerPort: 3000
          name: websocket
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "1"
            memory: 400Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
        {{- if .Values.zwaveVolumePath }}
        - mountPath: /dev/zwave
          name: zwavestick
        {{- end }}
        - mountPath: /usr/src/app/store
          name: zwave-data
        {{- if .Values.additionalMounts }}
          {{- .Values.additionalMounts | toYaml | nindent 8 }}
        {{- end }}
        # - mountPath: /usr/src/app/store/settings.json <-- if putting your settings.json in a secret
        #   name: config
        #   readOnly: true
        #   subPath: settings.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      # - name: config <-- if putting your settings.json in a secret
      #   secret:
      #     defaultMode: 420
      #     secretName: zwave-js-ui
      {{- if .Values.zwaveVolumePath }}
      - name: zwavestick
        hostPath:
#          # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
#          # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
          path: {{ .Values.zwaveVolumePath }}
          type: CharDevice
      {{- end }}
      {{- if .Values.additionalVolumes }}
        {{- .Values.additionalVolumes | toYaml | nindent 6 }}
      {{- end }}
#      - name: data
#        hostPath:
#          path: /zwave/data
    {{- if .Values.persistence.enabled }}
      - name: zwave-data
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.claimName }}
    {{- end }}
